### ISSUE TITLE
Alterando a Ficha Catalográfica e o Termo de Apresentação...

### ISSUE THREAD

**Issue by aweiand** [piccoli/PP-LaTeX#1]
Piccoli, gostaria de saber como posso fazer para alterar o texto da ficha catalográfica e o do termo de apresentação para o PDF fornecido pelo PPGCC, para poder deixar o arquivo correto e não necessitar utilizar outro programa para substituir estas páginas no PDF final.

**Comment by piccoli** [comment]
E aí Augusto, uma maneira que dá pra tentar é redefinir o comando `\fillers` no preâmbulo do teu documento. 

E aí na redefinição do comando  tu podes inserir os PDFs da ficha catalográfica e do termo de apresentação.

Por exemplo (usando o pacote `pdfpages` pra incluir PDFs)):

```latex
\usepackage{pdfpages}
\newcommand*{\putpdf}[1]{%  Talvez só o \includepdf seja necessário. Testar!
    \cleardoublepage    
    \thispagestyle{empty}
    \includepdf{#1}
    \newpage             
}

\renewcommand*{\fillers}{%
    \putpdf{FICHA.PDF}
    \putpdf{TERMO.PDF}
}
```

**Comment by piccoli** [comment]
(Patches são bem-vindos!! :)

**Comment by piccoli** [comment]
For the record: se tu quiseres simplesmente eliminar essas páginas da dissertação (pra uma versão pré-homologação por exemplo), dá pra resolver de uma forma mais simples:

```latex
\let\fillers\relax
```

no preâmbulo.

**Comment by aweiand** [comment]
Oi Piccoli!!

Tentei inserir este trecho de código do teu primeiro comentário e não deu certo, ele gera um monte de erros de todos os tipos... (estou usando o sharelatex) :(
Fiz testes inserindo o código no ".cls" e no "main.tex"...

O que funcionou foi o seguinte:

```
\newcommand*{\putpdf}[1]{%  Talvez só o \includepdf seja necessário. Testar!
    \cleardoublepage    
    \thispagestyle{empty}
    \includegraphics{#1}
    \newpage             
}

\renewcommand*{\fillers}{%
    \putpdf{FICHA.PDF}
    \putpdf{TERMO.PDF}
}
```

O problema é que ele não coloca a página com as margens em 0, então o PDF que é inserido fica no final da página, cortado...

**Comment by piccoli** [comment]
Tu sabes se o ShareLaTeX usa o `latex` ou o `pdflatex` pra compilar o documento?

Se for o `pdflatex`, temos que descobrir por que o `\includepdf` falhou.

Mas se funcionar com o `pdflatex`, o problema das margens se resolve fácil:

```latex
\includepdfset{pages=1,fitpaper=true}
```

**Comment by piccoli** [comment]
Tenta o seguinte. No preâmbulo:

```latex
\usepackage{pdfpages}
\includepdfset{pages=1,fitpaper=true}
\newcommand*{\putpdf}[1]{%
    \cleardoublepage    
    \thispagestyle{empty}
    \includepdf{#1}
    \newpage             
}
\let\fillers\relax
```

E imediatamente após o `\begin{document}`:

```latex
\putpdf{FICHA.PDF}
\putpdf{TERMO.PDF}
```

Um dos problemas é o momento em que o `\fillers`  é chamado pela classe, que está causando problemas pro `pdfpages`.

O outro problema é se a engine do LaTeX sendo usada não for o `pdfTeX`. Aí talvez tu tenhas que converter os teus PDFs para Postscript e usar o `\includegraphics` mesmo.

**Comment by aweiand** [comment]
Ele usa o `pdflatex` sim!

Agora sim!!! Funcionou perfeitamente com este último código!!!! :+1: :)

Muuuito obrigado!!
