### ISSUE TITLE
\simbolo apresentando erro com \overset

### ISSUE THREAD

**Issue by nielsenrechia** [piccoli/PP-LaTeX#15]
@olimarborges e demais

Acho que encontrie um possível problema. Vamos lá!

Ao longo do texto tenho os seguintes simbolos `$ A \overset{\subset}{\to} \{B_1, ..., B_k\}$` e ` $ A \overset{\subset}{\to} B$`. No texto eles ficam certinhos, o problema é quando coloco na lista de simbolos.

Fiz os comandos abaixo:

`\simbolo{$A \overset{\subset}{\to} \{B_1, ..., B_k\}$}{divisão de um perfil}`
`\simbolo{$ A \overset{\subset}{\to} B$}{absorção de um perfil}`

Quando compilo fica da seguinte maneira (print). No print coloquei outros simbolos que estão certinho, mas eles não usam o comando `\overset`, os quais são: `$A \to B$`, `$A \to \odot$` e `$\odot \to B$`. Para eles os simbolos foram criados conforme abaixo:
`\simbolo{$A \to B$}{sobrevivência de um perfil}`
`\simbolo{$A \to \odot$}{desaparecimento de um perfil}`
`\simbolo{$\odot \to B$}{surgimento de um perfil}`

Acredito que seja algo com o `\overset`, pois testei com todo o restante do conteúdo dos comandos (somente tirei `\overset`) e tudo compilou certinho. 
Em anexo também envio o log do erro.
![screenshot from 2019-02-13 10-41-24](https://user-images.githubusercontent.com/679126/52714862-1f5db680-2f82-11e9-98ed-a8f9f9d43070.png)
![screenshot from 2019-02-13 10-51-58](https://user-images.githubusercontent.com/679126/52714863-1f5db680-2f82-11e9-8fda-8325e93d1b1b.png)

**Comment by piccoli** [comment]
Oi Nielsen,

o que acontece nesse caso é que o comando `\overset` é _frágil_. Se olhares o conteúdo do arquivo `output.lob`, vais encontrar algo parecido com o seguinte no lugar do `\overset`:

```latex
$\begingroup \setbox \z@ \hbox {\thinmuskip 0mu \medmuskip \m@ne mu\thickmuskip \@ne mu \setbox \tw@ \hbox {$a\mathsurround \z@ $}\kern -\wd \tw@ ${}a{}\mathsurround \z@ $}\edef {\endgroup \let \binrel@@ \relax }\binrel@@ {\mathop {\kern \z@ a}\limits ^{*}}$\nobreakspace --\nobreakspace Ab
```
Como esses comandos são inválidos no contexto da lista de símbolos, a solução é _proteger_ o `\overset`, precedendo ele com o comando `\protect`. Por exemplo:

```latex
\simbolo{$\protect\overset{*}{A}$}{divisão de um perfil...} 
```

Isso deve resolver. De qualquer maneira, se conseguires testar isso e confirmar que funciona (ou não) te agradeço!

Obrigado!

**Comment by nielsenrechia** [comment]
Oi @piccoli 

Relamente, estavas certo. coloquei `\protect` e funcionou. Obrigado!
