### ISSUE TITLE
Alteração - proposta de tese em inglês

### ISSUE THREAD

**Issue by juliacolleoni** [piccoli/PP-LaTeX#16]
Olá,

No documento pucrs-ppgcc.cls, é necessário alterar linhas 259 e 261, para ajustar quando formos utilizar o idioma Inglês.
    \renewcommand*{\tese}{Dissertation} ------------> \renewcommand*{\tese}{Thesis}
    \renewcommand*{\ptese}{Dissertation proposal} --> \renewcommand*{\ptese}{Thesis proposal}

Obrigada :)

**Comment by piccoli** [comment]
Oi Júlia,

apesar dos significados de Thesis e Dissertation serem similares aos do Brasil em alguns países de língua inglesa, escolhemos usar Dissertation para tese de doutorado na época, pois é o mais comum nos EUA e o PPGCC ainda não tinha uma posição a respeito disso.

Como não sei se isso ainda é o caso, talvez o melhor seja usar um _default_ e permitir que o autor escolha o que achar mais adequado com um comando extra.

Obrigado pela contribuição!

**Comment by piccoli** [comment]
(Vou trabalhar nisso)

**Comment by piccoli** [comment]
Fechei, pois o Olimar já tinha feito essa correção e parece bem aceitável!
