### ISSUE TITLE
Warning on make clean

### ISSUE THREAD

**Issue by bonafernando** [piccoli/PP-LaTeX#17]
Ao rodar `make clean` aparece o seguinte warning:
```
$ make clean
latexmk -C
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at /usr/bin/latexmk line 3259.
```
Segui os passos de instalação do README.
Uso Ubuntu 18.04 e instalei com `sudo apt-get install texlive-full`

**Comment by piccoli** [comment]
Parece bem inofensivo o warning. O `latexmk` é escrito em Perl, então a mensagem deve resultar de uma combinação infeliz da versão do Perl com a versão do `latexmk` no Ubuntu.

De qualquer maneira, não há nada que possamos fazer (e não está prejudicando ninguém aparentemente!) :-).
