### ISSUE TITLE
Rotacionar uma imagem 90º

### ISSUE THREAD

**Issue by aweiand** [piccoli/PP-LaTeX#2]
Olá Piccoli!

Gostaria de saber se tens alguma dica para mim inserir uma imagem rotacionada em 90º anti-horário nos apêndices. Estou usando o seguinte código, mas ele acaba não inserindo a caption no sumário de figuras...

Muito obrigado!

```
\hvFloat[rotAngle=90]%
  {figure}
  {\centering%
  \includegraphics[scale=.43]{imgs_validacao/entrevista_pos__recorte_5_9.png}
  }
  {Tela da primeira semana.}%
  {fig:figure_bla}
```

**Comment by aweiand** [comment]
Acabei de descobrir que fazendo uma simples alteração ele vai para o sumário...
Eu não sabia que havia uma opção antes do texto que se usava para isto... segue o código funcionando... ;-)

```
\hvFloat[rotAngle=90]%
  {figure}
  {\centering%
  \includegraphics[scale=.43]{imgs_validacao/entrevista_pos__recorte_5_9.png}
  }
  [Faltou este texto...]{Tela da primeira semana.}%
  {fig:figure_bla}
```

**Comment by piccoli** [comment]
Legal! Mas esse comportamento (só inserir no sumário se tiver uma [short caption]) é do hvFloat né?  

Um problemão que essa classe do pós tem é que, pra não prejudicar a usabilidade, eu acabei redefinindo a implementação de uma série de comandos básicos do LaTeX (ao invés de usar as interfaces que o próprio LaTeX oferece pra fazer isso). 

A conseqüência disso é que alguns pacotes só funcionam se eu incluir modificações deles na própria classe, e por isso ela acaba inchando e "assimilando" código com o tempo... Felizmente, isso não tem acontecido com muita freqüência :)
