### ISSUE TITLE
Tipo de trabalho \ptese mostrando texto para grau de mestre

### ISSUE THREAD

**Issue by andersondomingues** [piccoli/PP-LaTeX#27]
Quando selecionado o tipo de trabalho "\ptese", o texto da página inicial mostra "degree of Master in Computer Science" em vez de doutor. Opção deveria ignorar a opção "\grau".

**Comment by piccoli** [comment]
Olá,

isso acontece somente quando ambas as opções `\tipotrabalho{\ptese}` e `\grau{mestre}` estão sendo usadas no documento? 

Se for o caso, eu concordo que essas linhas nunca devem ser usadas juntas, mas acho que é um problema inofensivo (já que a solução é simplesmente apagar o `\grau{mestre}`). A menos que isso dificulte o workflow de alguém, corrigir o problema vai acabar sendo mais custoso do que o benefício.

Obrigado!

**Comment by andersondomingues** [comment]
Claro, concordo. 

Acreditei que o que tipo de grau pode ser inferido do tipo de documento, e com isso removeria o parâmetro, mas realmente não atrapalha em nada.

**Comment by piccoli** [comment]
> Acreditei que o grau poderia ser inferido do tipo de documento, e com isso removeria o parâmetro, 

Idealmente, deveria ser o caso. :-)
