### ISSUE TITLE
Caixa de nome (autor) causa quebra de linha para nomes grandes

### ISSUE THREAD

**Issue by andersondomingues** [piccoli/PP-LaTeX#28]
Para nomes grandes (>= 29 caracteres), a caixa de nome do autor causa quebra de linha (último nome vai para a prox. linha). É contornável reduzindo o tamanho da fonte (embora não seja o ideal).

**Comment by piccoli** [comment]
Seria aceitável quebrar a regra e aumentar a largura da caixa do nome? Por outro lado, se o nome for tão comprido a ponto de cruzar as margens da página (que são razoavelmente largas na capa se não me falha a memória), teríamos menos opções (abreviar o nome, reduzir a fonte ou quebrar a linha). 

Da maneira como está feito hoje, a capa tem 5cm de margens e a caixa com o título e autor tem 11,5cm de largura, pois eu acho que é o tamanho do recorte da capa padrão da biblioteca da PUCRS: 

![image](https://user-images.githubusercontent.com/1672077/100000126-ecc02f00-2d9f-11eb-9504-8e401cf7fee5.png)

**Comment by andersondomingues** [comment]
No meu caso, meu último nome gerou uma nova linha e precisei usar "\small" para fazer meu nome ficar em uma linha só. Minha dissertação foi aprovada, então acho que a opção do "\small" não fere as regras (apesar de ter ficado diferente do padrão). Se é uma questão do padrão, acho que não precisar resolver aqui.

**Comment by piccoli** [comment]
Que bom que aprovaram! Como eu já saí do PPGCC há alguns anos, eu realmente não sei mais como anda a exigência em relação a essas questões, ou que tipo de flexibilização eles aceitam. 

Se quiseres fazer um teste com a largura da caixa, a alteração é simples:

```diff
diff --git a/pucrs-ppgcc.cls b/pucrs-ppgcc.cls
index f8b4bff..7bb2cf8 100644
--- a/pucrs-ppgcc.cls
+++ b/pucrs-ppgcc.cls
@@ -395,7 +395,7 @@ e-mail <rfbpiccoli at gmail dot com>^^J
         % Retângulo central (título + autor)
         %----------------------------------------------------------------------------------
         \hbox{\kern5cm\vbox to 7.7cm{%
-            \hsize=11.5cm
+            \hsize=12.5cm
             \parskip6ex
             \parindent0pt
             \leftskip0pt plus1fil
```

Nesse caso, o título vai aumentar de largura junto com o autor. De repente 1 centímetro já é o suficiente!
