### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by adrianovogel** [piccoli/PP-LaTeX#6]
CLS: "submitted to the \PP@Uni{} in partial **fullfillment** of
        the requirements for the degree of \PP@grau{} in Computer
        Science." 
fullfillment -> fulfillment

**Comment by piccoli** [comment]
Oops! Esse tempo todo e esse erro só aparece agora? :scream:

De qualquer maneira, já está corrigido no master. Valeu Adriano!!! :smile:

**Comment by piccoli** [comment]
Resolvido.

**Comment by adrianovogel** [comment]
Obrigado!
