### ISSUE TITLE
Escola Politécnica

### ISSUE THREAD

**Issue by heukirne** [piccoli/PP-LaTeX#7]
Oi Piccoli,

Agora não existe mais Faculdade de Informática, tem que trocar no template para Escola Politécnica.

Abraços,

**Comment by piccoli** [comment]
Integrado. Valeu Henrique!

**Comment by heukirne** [comment]
👏👏

Em sáb, 25 de ago de 2018 20:45, Ricardo Piccoli <notifications@github.com>
escreveu:
